name: flutix
version: 1.0.0+7
publish_to: none
description: Cinema Ticket Booking Application.
environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  change_app_package_name: ^1.1.0
  cloud_firestore: ^4.3.1
  colored_json: ^1.1.0
  cupertino_icons: ^1.0.2
  dio: ^4.0.6
  dropdown_button2: ^1.8.9
  easy_mask: ^2.0.1
  equatable: ^2.0.5
  firebase_auth: ^4.2.5
  firebase_core: ^2.4.1
  firebase_storage: ^11.0.10
  flutter:
    sdk: flutter
  flutter_jailbreak_detection: ^1.8.0
  flutter_launcher_icons: ^0.12.0
  flutter_screenutil: ^5.6.0
  flutter_spinkit: ^5.1.0
  flutter_typeahead: ^4.1.1
  fluttertoast: ^8.1.1
  get: ^4.6.5
  get_storage: ^2.0.3
  google_fonts: ^3.0.1
  image_picker: ^0.8.6
  intl: ^0.17.0
  jwt_decoder: ^2.0.1
  package_info_plus: ^3.0.1
  path: any
  permission_handler: ^10.2.0
  qr_flutter: ^4.0.0
  random_string: ^2.3.1
  shimmer: ^2.0.0
  smooth_page_indicator: ^1.0.0+2

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  lints: 2.0.1

flutter_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/icons/ic_launcher.png"

flutter:
  assets:
    - assets/logos/
    - assets/images/
    - assets/icons/
  uses-material-design: true
